
# Requirements
FROM --platform=linux/arm/v7 python:3.9-slim
COPY /requirements.txt /app/requirements.txt
WORKDIR /app
RUN apt-get update \
    && apt-get install -y libatlas-base-dev \
    && pip install --index-url=https://www.piwheels.org/simple --no-cache-dir -r requirements.txt

# Run App
COPY /static /app/static
COPY /templates /app/templates
COPY /run.py /app/run.py
ENTRYPOINT [ "python" ]
CMD ["run.py"]
