name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the tag
      id: vartag
      run: echo ::set-output name=tag::$(date +"%Y%m%d-%H%M%S")
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tim0-12432/mqtt-listener:${{ steps.vartag.outputs.tag }}
    - name: Push the tagged Docker image
      run: docker push ghcr.io/tim0-12432/mqtt-listener:${{ steps.vartag.outputs.tag }}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tim0-12432/mqtt-listener:latest
    - name: Push the latest Docker image
      run: docker push ghcr.io/tim0-12432/mqtt-listener:latest